### ISSUE TITLE
why return *this

### ISSUE THREAD

**Issue by sunjiweiswift** [mindspore-ai/graphengine#3]
https://github.com/mindspore-ai/graphengine/blob/cd365aa247c64e30487d1e71e4f724a889848f80/inc/external/graph/operator_reg.h#L68
这里为什么要调用OpReg().N()，来返回*this？？？感觉没用

**Comment by nicholasyanghaoran** [comment]
您好，非常感谢您的建议，N()在这个位置确实是不需要的，这里的本意是通过调用N()来拼接算子定义，不过return *this实际上没有起作用，我们会在后续版本中修正这个问题。还请继续支持MindSpore，谢谢！
